# Generated by Django 4.1 on 2022-09-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_actor_movie_actors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='Acto',
        ),
    ]
