# Generated by Django 4.1 on 2022-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_dressingroom_actor_dressing'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressingroom',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dressingroom',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
