# Generated by Django 4.1 on 2022-09-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0020_dressingroom_floor_dressingroom_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressingroom',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dressingroom',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
